version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  unit-tests:
    executor: python/default
    steps:
      - checkout
      - run:
          command: sudo python3 ./run_tests.py
          name: Unit tests

workflows:
  main:
    jobs:
      - unit-tests
